### ISSUE TITLE
Need custom text and static materials for icons, banner, colors, etc

### ISSUE THREAD

**Issue by emiliom** [BiG-CZ/notebook_data_demo#3]
From @ocefpaf: We need an intro text and more static material for icons, banner, colors, etc to make it look less like IOOS and more like BiG-CZ.

**Comment by lsetiawan** [comment]
Hi All, I have a proposition for the navbar and footer color:

NAVBAR: 
``` css
.masthead {
    background-color: #5E5C57
}

.greedy-nav { 
    background-color: #5E5C57
}
```
<img width="1421" alt="screen shot 2017-07-05 at 09 04 20" src="https://user-images.githubusercontent.com/17802172/27873483-2bc0f18a-6161-11e7-900c-d7036963af88.png">

FOOTER:
```css
/* For the background-image, can download it first... I just used the direct link for now */
.page__footer {
    background-image: url(http://portal.bigcz.org/local/images/framework/background-trans.png);
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
    background-color: hsl(45, 5%, 18%);
}
```
<img width="1421" alt="screen shot 2017-07-05 at 09 04 34" src="https://user-images.githubusercontent.com/17802172/27873482-2bb37dc0-6161-11e7-8039-637c3c302238.png">

**Comment by ocefpaf** [comment]
Much better @lsetiawan! I like it. I'm sending a PR with those now to check how it looks in my browsers.

**Comment by lsetiawan** [comment]
@ocefpaf what do you think of the html background-color change to: #F5F5F5?

<img width="819" alt="screen shot 2017-07-05 at 09 17 03" src="https://user-images.githubusercontent.com/17802172/27873981-bd46cdc2-6162-11e7-90b8-0c535c0c97dd.png">

**Comment by ocefpaf** [comment]
> @ocefpaf what do you think of the html background-color change to: #F5F5F5?

I kind of prefer the original one, but I don't really have a strong opinion for this one.

**Comment by lsetiawan** [comment]
> I kind of prefer the original one, but I don't really have a strong opinion for this one.

Alrighty. 😄 We'll wait for @emiliom maybe to decide on that one.

Also, I think that the pagination color should pop a little more..

```css
.pagination--pager {
    color: #818181;
}
```

<img width="442" alt="screen shot 2017-07-05 at 09 22 01" src="https://user-images.githubusercontent.com/17802172/27874175-76f07a84-6163-11e7-946f-b2a480d40246.png">
